-- Auto-generated SQL loader for synthetic data
-- Generated on: 2025-11-13 07:34:03.974974

USE health_insurance;

SET FOREIGN_KEY_CHECKS=0;
SET AUTOCOMMIT=0;

-- Load INSURANCE
TRUNCATE TABLE INSURANCE;
LOAD DATA LOCAL INFILE 'insurance.csv'
INTO TABLE INSURANCE
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load PLAN
TRUNCATE TABLE PLAN;
LOAD DATA LOCAL INFILE 'plan.csv'
INTO TABLE PLAN
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load FACILITY
TRUNCATE TABLE FACILITY;
LOAD DATA LOCAL INFILE 'facility.csv'
INTO TABLE FACILITY
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load CONDITION
TRUNCATE TABLE CONDITION;
LOAD DATA LOCAL INFILE 'condition.csv'
INTO TABLE CONDITION
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load MEMBERS
TRUNCATE TABLE MEMBERS;
LOAD DATA LOCAL INFILE 'members.csv'
INTO TABLE MEMBERS
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load ENROLLMENT
TRUNCATE TABLE ENROLLMENT;
LOAD DATA LOCAL INFILE 'enrollment.csv'
INTO TABLE ENROLLMENT
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load MEMBER_CONDITION
TRUNCATE TABLE MEMBER_CONDITION;
LOAD DATA LOCAL INFILE 'member_condition.csv'
INTO TABLE MEMBER_CONDITION
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load CLAIMS
TRUNCATE TABLE CLAIMS;
LOAD DATA LOCAL INFILE 'claims.csv'
INTO TABLE CLAIMS
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

COMMIT;
SET FOREIGN_KEY_CHECKS=1;

-- Verify row counts
SELECT 'INSURANCE' as 'Table', COUNT(*) as 'Rows' FROM INSURANCE;
SELECT 'PLAN' as 'Table', COUNT(*) as 'Rows' FROM PLAN;
SELECT 'FACILITY' as 'Table', COUNT(*) as 'Rows' FROM FACILITY;
SELECT 'CONDITION' as 'Table', COUNT(*) as 'Rows' FROM CONDITION;
SELECT 'MEMBERS' as 'Table', COUNT(*) as 'Rows' FROM MEMBERS;
SELECT 'ENROLLMENT' as 'Table', COUNT(*) as 'Rows' FROM ENROLLMENT;
SELECT 'MEMBER_CONDITION' as 'Table', COUNT(*) as 'Rows' FROM MEMBER_CONDITION;
SELECT 'CLAIMS' as 'Table', COUNT(*) as 'Rows' FROM CLAIMS;